__author__ = "John Machin"
__copyright__ = "Portions copyright © 2005-2009, Stephen John Machin, Lingfo Pty Ltd"
__email__ = "sjmachin@lexicon.net"
__license__ = "BSD"
__version__ = "3.0.0"
__maintainer__ = "Tsuyoshi Hombashi"
__maintainer_email__ = "tsuyoshi.hombashi@gmail.com"
