cache: pip

language: python

matrix:
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.5"
      env: TOXENV=py35

    - os: linux
      python: 3.8
      env: TOXENV=py38

    - os: linux
      python: 3.7
      env: TOXENV=cov
      after_success:
        - travis_retry pip install coveralls
        - coveralls

install:
  - travis_retry pip install tox

script:
  - tox
